const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('freska', {
  config: {
    obtenerTema: () => ipcRenderer.invoke('config:obtenerTema'),
    guardarTema: (tema) => ipcRenderer.invoke('config:guardarTema', tema),
    obtenerDireccionLocal: () => ipcRenderer.invoke('config:obtenerDireccionLocal'),
    obtenerZonaLocal: () => ipcRenderer.invoke('config:obtenerZonaLocal'),
    guardarZonaLocal: (zona) => ipcRenderer.invoke('config:guardarZonaLocal', zona),
    guardarDireccionLocal: (direccion) => ipcRenderer.invoke('config:guardarDireccionLocal', direccion),
    obtenerRetencionTransferencia: () => ipcRenderer.invoke('config:obtenerRetencionTransferencia'),
    guardarRetencionTransferencia: (porcentaje) => ipcRenderer.invoke('config:guardarRetencionTransferencia', porcentaje),
  },
  clientes: {
    listar: () => ipcRenderer.invoke('clientes:listar'),
    crear: (cliente) => ipcRenderer.invoke('clientes:crear', cliente),
    actualizar: (cliente) => ipcRenderer.invoke('clientes:actualizar', cliente),
    eliminar: (id) => ipcRenderer.invoke('clientes:eliminar', id),
    darDeBaja: (id) => ipcRenderer.invoke('clientes:darDeBaja', id),
    darDeAlta: (id) => ipcRenderer.invoke('clientes:darDeAlta', id),
    registrarConsulta: (id) => ipcRenderer.invoke('clientes:registrarConsulta', id),
    registrarPagoGeneral: (pago) => ipcRenderer.invoke('clientes:registrarPagoGeneral', pago),
    historial: (id) => ipcRenderer.invoke('clientes:historial', id),
    historialPagos: (id) => ipcRenderer.invoke('clientes:historialPagos', id),
    notasCredito: (id) => ipcRenderer.invoke('clientes:notasCredito', id),
    cobrosAnulados: (id) => ipcRenderer.invoke('clientes:cobrosAnulados', id),
  },
  productos: {
    listar: () => ipcRenderer.invoke('productos:listar'),
    crear: (producto) => ipcRenderer.invoke('productos:crear', producto),
    actualizar: (producto) => ipcRenderer.invoke('productos:actualizar', producto),
    baja: (id) => ipcRenderer.invoke('productos:baja', id),
  },
  metodosPago: {
    listar: () => ipcRenderer.invoke('metodosPago:listar'),
    crear: (nombre) => ipcRenderer.invoke('metodosPago:crear', nombre),
    actualizar: (metodo) => ipcRenderer.invoke('metodosPago:actualizar', metodo),
    baja: (id) => ipcRenderer.invoke('metodosPago:baja', id),
  },
  pedidos: {
    listar: () => ipcRenderer.invoke('pedidos:listar'),
    items: (pedidoId) => ipcRenderer.invoke('pedidos:items', pedidoId),
    crear: (pedido) => ipcRenderer.invoke('pedidos:crear', pedido),
    actualizar: (datos) => ipcRenderer.invoke('pedidos:actualizar', datos),
    marcarFacturado: (datos) => ipcRenderer.invoke('pedidos:marcarFacturado', datos),
    eliminar: (id) => ipcRenderer.invoke('pedidos:eliminar', id),
  },
  facturas: {
    listar: () => ipcRenderer.invoke('facturas:listar'),
    items: (facturaId) => ipcRenderer.invoke('facturas:items', facturaId),
    pagos: (facturaId) => ipcRenderer.invoke('facturas:pagos', facturaId),
    crear: (factura) => ipcRenderer.invoke('facturas:crear', factura),
    actualizar: (factura) => ipcRenderer.invoke('facturas:actualizar', factura),
    registrarPago: (pago) => ipcRenderer.invoke('facturas:registrarPago', pago),
    anular: (datos) => ipcRenderer.invoke('facturas:anular', datos),
    reactivar: (id) => ipcRenderer.invoke('facturas:reactivar', id),
  },
  tarjetas: {
    listar: () => ipcRenderer.invoke('tarjetas:listar'),
    crear: (datos) => ipcRenderer.invoke('tarjetas:crear', datos),
    quitar: (id) => ipcRenderer.invoke('tarjetas:quitar', id),
  },
  pagos: {
    cambiarMetodo: (datos) => ipcRenderer.invoke('pagos:cambiarMetodo', datos),
    anular: (datos) => ipcRenderer.invoke('pagos:anular', datos),
    reactivarCobro: (id) => ipcRenderer.invoke('pagos:reactivarCobro', id),
  },
  cuentas: {
    resumen: () => ipcRenderer.invoke('cuentas:resumen'),
    movimientos: (nombre) => ipcRenderer.invoke('cuentas:movimientos', nombre),
    guardarSaldos: (datos) => ipcRenderer.invoke('cuentas:guardarSaldos', datos),
    guardarDolares: (datos) => ipcRenderer.invoke('cuentas:guardarDolares', datos),
    ajustar: (datos) => ipcRenderer.invoke('cuentas:ajustar', datos),
  },
  carga: {
    hoy: () => ipcRenderer.invoke('carga:hoy'),
    marcar: (datos) => ipcRenderer.invoke('carga:marcar', datos),
    marcarTodos: (datos) => ipcRenderer.invoke('carga:marcarTodos', datos),
  },
  reportes: {
    cobrosPorDia: () => ipcRenderer.invoke('reportes:cobrosPorDia'),
    cobrosPorMes: () => ipcRenderer.invoke('reportes:cobrosPorMes'),
    cobrosDelDia: (fecha) => ipcRenderer.invoke('reportes:cobrosDelDia', fecha),
    saldosPorCliente: () => ipcRenderer.invoke('reportes:saldosPorCliente'),
    cantidadesPedidasPorDia: () => ipcRenderer.invoke('reportes:cantidadesPedidasPorDia'),
    cantidadesPedidasPorMes: () => ipcRenderer.invoke('reportes:cantidadesPedidasPorMes'),
  },
  cheques: {
    listar: (filtro) => ipcRenderer.invoke('cheques:listar', filtro),
    crear: (cheque) => ipcRenderer.invoke('cheques:crear', cheque),
    entregar: (datos) => ipcRenderer.invoke('cheques:entregar', datos),
    volverACartera: (id) => ipcRenderer.invoke('cheques:volverACartera', id),
    eliminar: (id) => ipcRenderer.invoke('cheques:eliminar', id),
  },
  avisos: {
    obtener: () => ipcRenderer.invoke('avisos:obtener'),
    tipos: () => ipcRenderer.invoke('avisos:tipos'),
    activar: (datos) => ipcRenderer.invoke('avisos:activar', datos),
    marcar: (datos) => ipcRenderer.invoke('avisos:marcar', datos),
  },
  buscar: {
    todo: (consulta) => ipcRenderer.invoke('buscar:todo', consulta),
  },
  estadisticas: {
    resumen: (filtro) => ipcRenderer.invoke('estadisticas:resumen', filtro),
    pendiente: () => ipcRenderer.invoke('estadisticas:pendiente'),
    rankings: (filtro) => ipcRenderer.invoke('estadisticas:rankings', filtro),
    preciosCompras: (filtro) => ipcRenderer.invoke('estadisticas:preciosCompras', filtro),
  },
  proveedores: {
    listar: () => ipcRenderer.invoke('proveedores:listar'),
    crear: (datos) => ipcRenderer.invoke('proveedores:crear', datos),
    actualizar: (datos) => ipcRenderer.invoke('proveedores:actualizar', datos),
    darDeBaja: (id) => ipcRenderer.invoke('proveedores:darDeBaja', id),
    darDeAlta: (id) => ipcRenderer.invoke('proveedores:darDeAlta', id),
    eliminar: (id) => ipcRenderer.invoke('proveedores:eliminar', id),
    historial: (id) => ipcRenderer.invoke('proveedores:historial', id),
    productosComprados: () => ipcRenderer.invoke('proveedores:productosComprados'),
    tipos: () => ipcRenderer.invoke('proveedores:tipos'),
    agregarTipo: (nombre) => ipcRenderer.invoke('proveedores:agregarTipo', nombre),
    quitarTipo: (id) => ipcRenderer.invoke('proveedores:quitarTipo', id),
    productos: (proveedorId) => ipcRenderer.invoke('proveedores:productos', proveedorId),
    agregarProducto: (datos) => ipcRenderer.invoke('proveedores:agregarProducto', datos),
    quitarProducto: (id) => ipcRenderer.invoke('proveedores:quitarProducto', id),
    crearCompra: (compra) => ipcRenderer.invoke('proveedores:crearCompra', compra),
    actualizarCompra: (compra) => ipcRenderer.invoke('proveedores:actualizarCompra', compra),
    quitarCompra: (id) => ipcRenderer.invoke('proveedores:quitarCompra', id),
    pagar: (pago) => ipcRenderer.invoke('proveedores:pagar', pago),
    actualizarPago: (pago) => ipcRenderer.invoke('proveedores:actualizarPago', pago),
    devolver: (datos) => ipcRenderer.invoke('proveedores:devolver', datos),
    quitarDevolucion: (id) => ipcRenderer.invoke('proveedores:quitarDevolucion', id),
    quitarPago: (id) => ipcRenderer.invoke('proveedores:quitarPago', id),
    totalPagos: (filtro) => ipcRenderer.invoke('proveedores:totalPagos', filtro),
  },
  insumos: {
    listar: () => ipcRenderer.invoke('insumos:listar'),
    crear: (datos) => ipcRenderer.invoke('insumos:crear', datos),
    actualizar: (datos) => ipcRenderer.invoke('insumos:actualizar', datos),
    quitar: (id) => ipcRenderer.invoke('insumos:quitar', id),
    contar: (datos) => ipcRenderer.invoke('insumos:contar', datos),
    conteos: (id) => ipcRenderer.invoke('insumos:conteos', id),
    quitarConteo: (id) => ipcRenderer.invoke('insumos:quitarConteo', id),
  },
  stock: {
    resumen: () => ipcRenderer.invoke('stock:resumen'),
    rendimiento: (periodo) => ipcRenderer.invoke('stock:rendimiento', periodo),
    actualizarCarne: (datos) => ipcRenderer.invoke('stock:actualizarCarne', datos),
    actualizarMinimo: (datos) => ipcRenderer.invoke('stock:actualizarMinimo', datos),
    crearArticulo: (nombre) => ipcRenderer.invoke('stock:crearArticulo', nombre),
    quitarArticulo: (id) => ipcRenderer.invoke('stock:quitarArticulo', id),
    actualizarTipo: (datos) => ipcRenderer.invoke('stock:actualizarTipo', datos),
    actualizarCarnes: (datos) => ipcRenderer.invoke('stock:actualizarCarnes', datos),
    producidoPorArticulo: (datos) => ipcRenderer.invoke('stock:producidoPorArticulo', datos),
    sinTipo: (datos) => ipcRenderer.invoke('stock:sinTipo', datos),
    tiposCarne: () => ipcRenderer.invoke('stock:tiposCarne'),
    agregarTipoCarne: (nombre) => ipcRenderer.invoke('stock:agregarTipoCarne', nombre),
    quitarTipoCarne: (id) => ipcRenderer.invoke('stock:quitarTipoCarne', id),
    vincular: (datos) => ipcRenderer.invoke('stock:vincular', datos),
    producir: (datos) => ipcRenderer.invoke('stock:producir', datos),
    ajustar: (datos) => ipcRenderer.invoke('stock:ajustar', datos),
    movimientos: (filtro) => ipcRenderer.invoke('stock:movimientos', filtro),
    quitarMovimiento: (id) => ipcRenderer.invoke('stock:quitarMovimiento', id),
  },
  inflacion: {
    listar: () => ipcRenderer.invoke('inflacion:listar'),
    guardar: (datos) => ipcRenderer.invoke('inflacion:guardar', datos),
  },
  operaciones: {
    listar: () => ipcRenderer.invoke('operaciones:listar'),
    pase: (datos) => ipcRenderer.invoke('operaciones:pase', datos),
    comprarDolares: (datos) => ipcRenderer.invoke('operaciones:comprarDolares', datos),
    canjearCheque: (datos) => ipcRenderer.invoke('operaciones:canjearCheque', datos),
    interes: (datos) => ipcRenderer.invoke('operaciones:interes', datos),
    reintegro: (datos) => ipcRenderer.invoke('operaciones:reintegro', datos),
    eliminar: (id) => ipcRenderer.invoke('operaciones:eliminar', id),
  },
  ingresos: {
    listar: () => ipcRenderer.invoke('ingresos:listar'),
    crear: (datos) => ipcRenderer.invoke('ingresos:crear', datos),
    eliminar: (id) => ipcRenderer.invoke('ingresos:eliminar', id),
    resultado: (rango) => ipcRenderer.invoke('ingresos:resultado', rango),
    resultadoDetalle: (datos) => ipcRenderer.invoke('ingresos:resultadoDetalle', datos),
    categorias: () => ipcRenderer.invoke('ingresos:categorias'),
    crearCategoria: (nombre) => ipcRenderer.invoke('ingresos:crearCategoria', nombre),
    quitarCategoria: (id) => ipcRenderer.invoke('ingresos:quitarCategoria', id),
    categoriasGastosPersonales: () => ipcRenderer.invoke('ingresos:categoriasGastosPersonales'),
    crearCategoriaGastoPersonal: (nombre) => ipcRenderer.invoke('ingresos:crearCategoriaGastoPersonal', nombre),
    quitarCategoriaGastoPersonal: (id) => ipcRenderer.invoke('ingresos:quitarCategoriaGastoPersonal', id),
    descripciones: () => ipcRenderer.invoke('ingresos:descripciones'),
    crearDescripcion: (datos) => ipcRenderer.invoke('ingresos:crearDescripcion', datos),
    rendimiento: (datos) => ipcRenderer.invoke('ingresos:rendimiento', datos),
    reintegro: (datos) => ipcRenderer.invoke('ingresos:reintegro', datos),
    quitarDescripcion: (id) => ipcRenderer.invoke('ingresos:quitarDescripcion', id),
    saldos: () => ipcRenderer.invoke('ingresos:saldos'),
    guardarDolares: (datos) => ipcRenderer.invoke('ingresos:guardarDolares', datos),
    comprarDolares: (datos) => ipcRenderer.invoke('ingresos:comprarDolares', datos),
    comprasDolares: () => ipcRenderer.invoke('ingresos:comprasDolares'),
    eliminarCompraDolares: (id) => ipcRenderer.invoke('ingresos:eliminarCompraDolares', id),
    movimientos: (cuenta) => ipcRenderer.invoke('ingresos:movimientos', cuenta),
    ajustarSaldo: (datos) => ipcRenderer.invoke('ingresos:ajustarSaldo', datos),
    retiros: () => ipcRenderer.invoke('ingresos:retiros'),
    crearRetiro: (datos) => ipcRenderer.invoke('ingresos:crearRetiro', datos),
    eliminarRetiro: (id) => ipcRenderer.invoke('ingresos:eliminarRetiro', id),
    pases: () => ipcRenderer.invoke('ingresos:pases'),
    crearPase: (datos) => ipcRenderer.invoke('ingresos:crearPase', datos),
    eliminarPase: (id) => ipcRenderer.invoke('ingresos:eliminarPase', id),
  },
  gastos: {
    categorias: () => ipcRenderer.invoke('gastos:categorias'),
    crearCategoria: (nombre) => ipcRenderer.invoke('gastos:crearCategoria', nombre),
    quitarCategoria: (id) => ipcRenderer.invoke('gastos:quitarCategoria', id),
    cambiarAmbitoCategoria: (datos) => ipcRenderer.invoke('gastos:cambiarAmbitoCategoria', datos),
    descripciones: () => ipcRenderer.invoke('gastos:descripciones'),
    crearDescripcion: (datos) => ipcRenderer.invoke('gastos:crearDescripcion', datos),
    quitarDescripcion: (id) => ipcRenderer.invoke('gastos:quitarDescripcion', id),
    crear: (gasto) => ipcRenderer.invoke('gastos:crear', gasto),
    actualizar: (gasto) => ipcRenderer.invoke('gastos:actualizar', gasto),
    eliminar: (id) => ipcRenderer.invoke('gastos:eliminar', id),
    listar: (filtro) => ipcRenderer.invoke('gastos:listar', filtro),
    cuotas: (gastoId) => ipcRenderer.invoke('gastos:cuotas', gastoId),
    cuotasPendientes: () => ipcRenderer.invoke('gastos:cuotasPendientes'),
    pagarCuota: (datos) => ipcRenderer.invoke('gastos:pagarCuota', datos),
    deshacerCuota: (id) => ipcRenderer.invoke('gastos:deshacerCuota', id),
  },
  caja: {
    obtenerDia: (fecha) => ipcRenderer.invoke('caja:obtenerDia', fecha),
    resumenCierres: () => ipcRenderer.invoke('caja:resumenCierres'),
    resumenMes: (datos) => ipcRenderer.invoke('caja:resumenMes', datos),
    guardarCierre: (datos) => ipcRenderer.invoke('caja:guardarCierre', datos),
  },
  sistema: {
    abrirEnlace: (url) => ipcRenderer.invoke('sistema:abrirEnlace', url),
    buscarActualizacion: () => ipcRenderer.invoke('sistema:buscarActualizacion'),
    instalarActualizacion: () => ipcRenderer.invoke('sistema:instalarActualizacion'),
    hacerBackup: () => ipcRenderer.invoke('sistema:hacerBackup'),
    listarCopias: () => ipcRenderer.invoke('sistema:listarCopias'),
    abrirCarpetaCopias: () => ipcRenderer.invoke('sistema:abrirCarpetaCopias'),
    copiaExternaEstado: () => ipcRenderer.invoke('sistema:copiaExternaEstado'),
    elegirCarpetaCopiaExterna: () => ipcRenderer.invoke('sistema:elegirCarpetaCopiaExterna'),
    copiaExternaAhora: () => ipcRenderer.invoke('sistema:copiaExternaAhora'),
    quitarCopiaExterna: () => ipcRenderer.invoke('sistema:quitarCopiaExterna'),
    restaurarCopia: (nombre) => ipcRenderer.invoke('sistema:restaurarCopia', nombre),
    restaurarDesdeArchivo: () => ipcRenderer.invoke('sistema:restaurarDesdeArchivo'),
    geocodificar: (direccion) => ipcRenderer.invoke('sistema:geocodificar', direccion),
  },
  usuarios: {
    paraElegir: () => ipcRenderer.invoke('usuarios:paraElegir'),
    crearPrimero: (datos) => ipcRenderer.invoke('usuarios:crearPrimero', datos),
    ingresar: (datos) => ipcRenderer.invoke('usuarios:ingresar', datos),
    cerrarSesion: () => ipcRenderer.invoke('usuarios:cerrarSesion'),
    sesionActual: () => ipcRenderer.invoke('usuarios:sesionActual'),
    listar: () => ipcRenderer.invoke('usuarios:listar'),
    crear: (datos) => ipcRenderer.invoke('usuarios:crear', datos),
    actualizar: (datos) => ipcRenderer.invoke('usuarios:actualizar', datos),
    resetearPin: (datos) => ipcRenderer.invoke('usuarios:resetearPin', datos),
    cambiarPin: (datos) => ipcRenderer.invoke('usuarios:cambiarPin', datos),
  },
  vendedores: {
    listar: () => ipcRenderer.invoke('vendedores:listar'),
    crear: (datos) => ipcRenderer.invoke('vendedores:crear', datos),
    actualizar: (datos) => ipcRenderer.invoke('vendedores:actualizar', datos),
    informe: (mes) => ipcRenderer.invoke('vendedores:informe', mes),
    pagarComision: (datos) => ipcRenderer.invoke('vendedores:pagarComision', datos),
    deshacerPagoComision: (datos) => ipcRenderer.invoke('vendedores:deshacerPagoComision', datos),
  },
});
